name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    strategy:
      matrix:
        node-version: [18, "lts/*", "latest"]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm install
    - run: npm run sizewatcher
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: ${{ matrix.node-version == 'lts/*' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
